### ISSUE TITLE
[server] feature / DB 구축

### ISSUE THREAD

**Issue by G-Ryu** [codestates/Birth-Wiki-server#2]
### ISSUE

- Group: `server`
- Type: `feature`
- Detail: database migration & model define

### TODO

1.  [x] create - rds, database
2.  [x] define - migration key relation
3.  [x] define - model associate

### Labels

- Estimated time: `E: 2h`
- Group : `server`
- Sprint: ``
- Urgency: `Middle`
