### ISSUE TITLE
[server] feature / 엔드포인트 별 라우팅 /user

### ISSUE THREAD

**Issue by G-Ryu** [codestates/Birth-Wiki-server#3]
### ISSUE

- Group: `server`
- Type: `feature`
- Detail: routing endpoint /user

### TODO

1.  [x] log in/out
2.  [x] sign up/out
3.  [x] update userinfo
4.  [x] duplicate check - email & nickname
5.  [x] social - google
6.  [x] social - kakao
7.  [x] social - naver
8.  [x] get userinfo
9.  [x] get likecards 

### Estimated time

> Pick one

### Labels

- Estimated time: `E: 3h`
- Group : `server`
- Sprint: ``
- Urgency: `Middle`
