### ISSUE TITLE
[server] feature / 엔드포인트 별 라우팅 /date, /like

### ISSUE THREAD

**Issue by G-Ryu** [codestates/Birth-Wiki-server#7]
### ISSUE

- Group: `server`
- Type: `feature`
- Detail: routing endpoint /date, /like

### TODO

1.  [ ] data with nickname - date
2.  [ ] data with nickname - like
3.  [ ] data without nickname - date
4.  [ ] data without nickname - like

### Labels

- Estimated time: `E: 3h`
- Group : `server`
- Sprint: ``
- Urgency: `Middle`
