### ISSUE TITLE
[server] feature / 엔드포인트 별 라우팅 /record

### ISSUE THREAD

**Issue by G-Ryu** [codestates/Birth-Wiki-server#8]
### ISSUE

- Group: `server`
- Type: `feature`
- Detail: routing endpoint /record

### TODO

1.  [ ] create - record card
2.  [ ] update - record card
3.  [ ] delete - record card
4.  [ ] authority - public / private

### Estimated time

> Pick one

### Labels

- Estimated time: `E: 3h`
- Group : `server`
- Sprint: ``
- Urgency: `Middle`
